[tox]
envlist = py310, py311, py312, py313, py314
isolated_build = True

[testenv]
deps =
    Cython>=3.1.4
    pytest
    pytest-asyncio
    asyncio
    uvloop>=0.22.1; sys_platform != 'win32'
commands =
    python setup.py build_ext --inplace
    pytest tests/

[testenv:py310]
deps =
    {[testenv]deps}

[testenv:py311]
deps =
    {[testenv]deps}

[testenv:py312]
deps =
    {[testenv]deps}
