import logging


class Logger:
    def disable(self, name: str, loglevel = logging.CRITICAL) -> None: ...
    def setName(self, name: str) -> None: ...
    def info(self, message, *args, serialize = True, **kwargs) -> None: ...
    def debug(self, message, *args, serialize = True, **kwargs) -> None: ...
    def warning(self, message, *args, **kwargs) -> None: ...
