name: Build and Publish Python 🐍 distributions 📦 to PyPI and TestPyPI
on:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.5.0-manylinux2014_x86_64
      with:
        python-versions: 'cp38-cp38 cp39-cp39'
        build-requirements: 'cython numpy'
    - name: Publish wheels to Test PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.NAVCONFIG_TEST_PYPI_API_TOKEN }}
      run: |
        twine upload -r testpypi dist/*
    - name: Publish wheels to Production PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.NAVCONFIG_PYPI_API_TOKEN }}
      run: |
        twine upload  dist/*
